@echo off
REM Load environment variables from .env.local
node -e "require('dotenv').config({path: '.env.local'}); console.log('API Key:', process.env.NEXT_PUBLIC_FIREBASE_API_KEY?.substring(0, 5) + '...');"

set NEXT_PUBLIC_FIREBASE_API_KEY=%NEXT_PUBLIC_FIREBASE_API_KEY%
set NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=%NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN%
set NEXT_PUBLIC_FIREBASE_PROJECT_ID=%NEXT_PUBLIC_FIREBASE_PROJECT_ID%
set NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=%NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET%
set NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=%NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID%
set NEXT_PUBLIC_FIREBASE_APP_ID=%NEXT_PUBLIC_FIREBASE_APP_ID%
set NEXT_PUBLIC_ADMIN_EMAIL=%NEXT_PUBLIC_ADMIN_EMAIL%

npm run seed
pause
